spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: logs/prod.log
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.senla: TRACE

jwt:
  secret:
    key: 045Pg0+Uh2FPNTgus9OeZ83npvpAROFtcHuNsvk4Ej0=
  lifetime: 86400000
