spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

logging:
  level:
    root: debug
    org.springframework: INFO
    org.hibernate: DEBUG
    com.zaxxer.hikari: WARN
