spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: validate



logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss} 
      %highlight(%-5level){FATAL=red,ERROR=boldRed,WARN=yellow,INFO=green,DEBUG=cyan,TRACE=magenta} 
      [%boldBlue(%thread)] 
      %boldMagenta(%logger{36}) 
      - %msg
  file:
    name: logs/dev.log
  level:
    root: debug

jwt:
  secret:
    key: 045Pg0+Uh2FPNTgus9OeZ83npvpAROFtcHuNsvk4Ej0=
  lifetime: 3600000
